# yaml-language-server: $schema=./values.schema.json

global:
  domain: f087b35.kyma.ondemand.com
  imagePullSecret:
    name: docker-registry
  image:
    registry: nicoz91
    tag: 1.0.0
srv:
  bindings:
    destination:
      serviceInstanceName: 'destination'
    db:
      serviceInstanceName: hana
    auth:
      serviceInstanceName: xsuaa
  image:
    repository: incident-management-srv
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /health
    readiness:
      path: /health
destination:
  serviceOfferingName: 'destination'
  servicePlanName: 'lite'
  parameters:
    version: '1.0.0'
hana-deployer:
  image:
    repository: incident-management-hana-deployer
  bindings:
    hana:
      serviceInstanceName: hana
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
hana:
  serviceOfferingName: hana
  servicePlanName: hdi-shared
xsuaa:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    tenant-mode: dedicated
    xsappname: incident-management-{{ .Release.Namespace }}
